language: node_js
node_js:
  - "9"

env:
  global:
    - NODE_ENV=test
    - PGPASSWORD=af2018
    - DB_USER=muse
    - DB_PASS=af2018
    - DB_NAME=muse_test
    - DB_HOST=localhost
    - DB_PORT=5432

services:
  - postgresql


before_script:
  - psql -c "CREATE DATABASE muse_test;" -U postgres
  - psql -c "CREATE ROLE muse WITH PASSWORD 'af2018';" -U postgres
  - psql -c "ALTER ROLE muse WITH LOGIN;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE muse_test TO muse;" -U postgres
  - psql -d muse_test -U muse -f schema.sql;

script:
  - jest
