language: node_js
node_js:
  - "9"

env:
  global:
    - NODE_ENV=test
    - PGPASSWORD=af2018
    - DB_USER_TEST=muse
    - DB_PASS_TEST=af2018
    - DB_NAME_TEST=muse_test
    - DB_HOST=localhost
    - DB_PORT=5432

services:
  - postgresql

sudo: required
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install elm -g
  - npm install

before_script:
  - psql -c "CREATE DATABASE muse_test;" -U postgres
  - psql -c "CREATE ROLE muse WITH PASSWORD 'af2018';" -U postgres
  - psql -c "ALTER ROLE muse WITH LOGIN;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE muse_test TO muse;" -U postgres
  - psql -d muse_test -U muse -f schema.sql;

script:
  - npm run build
  - npm test
  - node ./bin/www &
  - npm run e2e
