language: node_js
node_js:
  - "8"

env:
  global:
    - DB_USER=muse
    - PGPASSWORD=af2018
    - DB_PASS=af2018
    - DB_NAME=muse_test
    - NODE_ENV=test

services:
  - postgresql

before_script:
  - env
  - psql -c "CREATE DATABASE muse_test;" -U postgres
  - psql -c "CREATE ROLE muse WITH PASSWORD 'af2018';" -U postgres
  - psql -c "ALTER ROLE muse WITH LOGIN;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE muse_test TO muse;" -U postgres
  - psql -d muse_test -U muse -f schema.sql;
