CREATE ROLE muse WITH LOGIN PASSWORD '[pw here]';
CREATE DATABASE muse;
GRANT ALL PRIVILEGES ON DATABASE muse TO muse;
\c muse;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR
);

ALTER TABLE users OWNER TO muse;

CREATE TABLE groups (
  id SERIAL PRIMARY KEY,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR
);

ALTER TABLE groups OWNER TO muse;


CREATE TABLE groupings (
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  group_id INT,
  PRIMARY KEY (user_id, group_id)
);

ALTER TABLE groupings OWNER TO muse;

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  song_id INT NOT NULL,
  body VARCHAR
);

ALTER TABLE comments OWNER TO muse;

CREATE TABLE songs (
  id SERIAL PRIMARY KEY,
  group_id INT NOT NULL,
  album VARCHAR,
  artist VARCHAR,
  length INT NOT NULL,
  name VARCHAR
);

ALTER TABLE songs OWNER TO muse;
